FROM ekidd/rust-musl-builder:stable as builder
WORKDIR /home/rust
COPY . .
RUN cargo build --release

FROM alpine:latest
WORKDIR /simple_rest
COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/simple_rest .
EXPOSE 8999
ENTRYPOINT [ "./simple_rest" ]

